language: c
compiler:
  - gcc
  - clang
notifications:
  recipients:
    - kenhys@gmail.com
branches:
  only:
    - master
env:
  - SYLPHEED_STAGE=master
  - SYLPHEED_STAGE=3.5
  - SYLPHEED_STAGE=3.4
before_script:
  - curl --location https://github.com/kenhys/sylpheed-plugin-factory/raw/master/misc/travis/sylpheed.sh | sh
  - curl --location https://github.com/kenhys/sylpheed-plugin-factory/raw/master/misc/travis/sylplugin-factory.sh | sh
  - ./autogen.sh
script:
  - curl https://raw.github.com/kenhys/sylpheed-plugin-factory/master/misc/travis/configure.sh | sh
  - make
